name: BaseCTF
main: com.pickuperic.Main
version: 1.0
commands:
  placeflag:
    description: Places flag on player's location
    usage: /placeflag
  getflag:
    description: Get location of specified team's flag
    usage: /flag
  setteam:
    description: Sets the specified user's specified team
    usage: /setteam